export const RECIEVE_MESSAGES = 'recieve_messages'
export const LOGIN_USER = 'login_user'
export const LOGIN_USER_FETCH = 'login_user_fetch'
export const LOGIN_USER_ERROR = 'login_user_error'
export const LOGOUT = 'logout'
